### ISSUE TITLE
Panels should not be dragable or resizable

### ISSUE THREAD

**Issue by james-darkfox** [Kintaro/wtftw#42] opened 2014-12-30 04:11 UTC
Xmobar will quickly move itself back should it be moved. Dzen2 however, will happily be moved and resized. Neither of these should be applied to the moving and resizing logic.

Another note: dzen2 doesn't get panel space allocated like xmobar does.

**Comment by Kintaro** [comment] 2015-01-13 19:44
Dzen2 seems to be unable to correctly allocate struts in xlib. So, either dzen2 should get fixed in that regard, or I'll make a "panel" layout that can at least be configured to make space for dzen.
The reason dzen can be moved is that very reason. It doesn't set any strut flags and fails to tell xlib that it is a dock window.

**Comment by james-darkfox** [comment] 2015-01-17 04:32
xmobar can be moved and resized... It just moves (and resizes) itself back when you try.

**Comment by Kintaro** [comment] 2015-01-18 04:58
That's something I wasn't able to reproduce at all. I've tried arch, gentoo, debian, ubuntu, even freebsd...for the love of god I cannot move it _at all_ :D

**Comment by james-darkfox** [comment] 2015-01-20 09:03
I assure you that I can here on ArchLinux inside Xnest.

**Comment by Kintaro** [comment] 2015-01-20 11:41
Since an update on my gentoo machine I can move it too. But I don't know how to classify this...Leave it as is because xmobar jumps back anyway? 

Will reopen it until I have time to fix it. Sorry, I'm a bit busy with my thesis at the moment.

**Closed** 2016-12-16 08:24 UTC
Labels: I-bug
